# TODO: use version derived from git revision
cvrf2csaf_version: 1.0
cvrf2csaf_name: CVRF-CSAF-Converter

# Document Publisher
publisher_name: Publisher Name
publisher_namespace: Publisher Namespace

# Document Tracking
force_update_revision_history: false
